<%@ page language="java" isELIgnored="false" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<span class="footer">Generated by <a href="http://www.myeclipseide.com/spring.php">MyEclipse for Spring</a><br>Copyright &copy; 2011 All Rights Reserved</span> 

