<?xml version="1.0" encoding="ASCII"?>
<skyway:SkywayService xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:generation="generation" xmlns:skyway="model.service.skyway" xmlns:type="model.type" description="Spring service that handles CRUD requests for Content entities"><extrinsics xsi:type="generation:CoreGenerationModel"/><variables description="DAO injected by Spring that manages Content entities" name="contentDAO"><modifiers>PRIVATE</modifiers><dataType xsi:type="type:BeanType"><type href="../../dao/ContentDAO/.properties.datastore#/"/></dataType></variables><variables description="DAO injected by Spring that manages Accomodation entities" name="accomodationDAO"><modifiers>PRIVATE</modifiers><dataType xsi:type="type:BeanType"><type href="../../dao/AccomodationDAO/.properties.datastore#/"/></dataType></variables></skyway:SkywayService>
